# Generated by Django 3.2.7 on 2021-09-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField(blank=True, null=True, verbose_name='Дата поствки')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('count', models.SmallIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Длина(расстояние)в ММ')),
            ],
        ),
    ]
