# Generated by Django 3.2.7 on 2021-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поставки'),
        ),
    ]
