# Generated by Django 3.2.7 on 2021-09-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_instruments_in_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruments',
            new_name='Instrument',
        ),
    ]
